platform :ios, "7.0"

pod "ASCScreenBrightnessDetector", :path => "../ASCScreenBrightnessDetector.podspec"

target "ASCScreenBrightnessDetectorExampleTests" do
	pod 'Specta'
	pod 'Expecta'
	pod 'OCMockito'
end
